In [1]:
import pandas as pd 
import numpy as np
import tensorflow as tf
tf.keras.backend.set_floatx('float64') # Removes the TensorFlow warnings considering the Data Types
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',header=None,
                 names=['Sepal Length','Sepal Width','Petal Length','Petal Width','Class'])
df

     Sepal Length  Sepal Width  Petal Length  Petal Width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [2]:
df['Class'] = pd.Categorical(df['Class'])  # https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html
df['Class'] = df['Class'].cat.codes
df

     Sepal Length  Sepal Width  Petal Length  Petal Width  Class
0             5.1          3.5           1.4          0.2      0
1             4.9          3.0           1.4          0.2      0
2             4.7          3.2           1.3          0.2      0
3             4.6          3.1           1.5          0.2      0
4             5.0          3.6           1.4          0.2      0
..            ...          ...           ...          ...    ...
145           6.7          3.0           5.2          2.3      2
146           6.3          2.5           5.0          1.9      2
147           6.5          3.0           5.2          2.0      2
148           6.2          3.4           5.4          2.3      2
149           5.9          3.0           5.1          1.8      2

[150 rows x 5 columns]

In [3]:
#tf.keras.set_random_seed(42) # For reproducibility
tf.keras.utils.set_random_seed(42) # For reproducibility
tf.keras.backend.set_floatx('float64') # Removes the TensorFlow warnings considering the Data Types

In [4]:
model_sequential = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(4,)),
    #tf.keras.InputLayer(input_shape=(4,)),
    # tf.keras.layers.Dense(10, activation='relu', input_shape=(4,)),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
])

In [5]:
inputs = tf.keras.Input(shape=(4,))
hidden = tf.keras.layers.Dense(10, activation='relu')(inputs)
outputs = tf.keras.layers.Dense(3, activation='softmax')(hidden)
model_functional = tf.keras.Model(inputs=inputs, outputs=outputs)

In [6]:
print(model_sequential.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 10)             │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 83 (664.00 B)

 Trainable params: 83 (664.00 B)

 Non-trainable params: 0 (0.00 B)

None

In [7]:
print(model_functional.summary())

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 4)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 83 (664.00 B)

 Trainable params: 83 (664.00 B)

 Non-trainable params: 0 (0.00 B)

None

In [8]:
# optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
# loss_fn = tf.keras.losses.SparseCategoricalCrossentropy()
# accuracy_metric = tf.keras.metrics.SparseCategoricalAccuracy()

model_sequential.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
#model_functional.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model_functional.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [9]:
history_sequential = model_sequential.fit(df.iloc[:,0:4], df.iloc[:,4], epochs=10, verbose=2)

Epoch 1/10
5/5 - 0s - 44ms/step - accuracy: 0.3333 - loss: 3.8384
Epoch 2/10
5/5 - 0s - 2ms/step - accuracy: 0.3333 - loss: 3.5368
Epoch 3/10
5/5 - 0s - 2ms/step - accuracy: 0.3333 - loss: 3.2403
Epoch 4/10
5/5 - 0s - 2ms/step - accuracy: 0.3333 - loss: 2.9498
Epoch 5/10
5/5 - 0s - 2ms/step - accuracy: 0.3333 - loss: 2.6663
Epoch 6/10
5/5 - 0s - 2ms/step - accuracy: 0.3333 - loss: 2.3922
Epoch 7/10
5/5 - 0s - 2ms/step - accuracy: 0.3333 - loss: 2.1304
Epoch 8/10
5/5 - 0s - 2ms/step - accuracy: 0.3333 - loss: 1.8831
Epoch 9/10
5/5 - 0s - 2ms/step - accuracy: 0.3333 - loss: 1.6531
Epoch 10/10
5/5 - 0s - 2ms/step - accuracy: 0.3333 - loss: 1.4448

In [10]:
history_functional = model_functional.fit(df.iloc[:,0:4], df.iloc[:,4], epochs=10, verbose=2)

Epoch 1/10
5/5 - 0s - 45ms/step - accuracy: 0.3333 - loss: 5.1298
Epoch 2/10
5/5 - 0s - 2ms/step - accuracy: 0.3333 - loss: 4.8799
Epoch 3/10
5/5 - 0s - 3ms/step - accuracy: 0.3333 - loss: 4.6359
Epoch 4/10
5/5 - 0s - 3ms/step - accuracy: 0.3333 - loss: 4.3976
Epoch 5/10
5/5 - 0s - 3ms/step - accuracy: 0.3333 - loss: 4.1649
Epoch 6/10
5/5 - 0s - 3ms/step - accuracy: 0.3333 - loss: 3.9378
Epoch 7/10
5/5 - 0s - 3ms/step - accuracy: 0.3333 - loss: 3.7162
Epoch 8/10
5/5 - 0s - 2ms/step - accuracy: 0.3333 - loss: 3.5004
Epoch 9/10
5/5 - 0s - 3ms/step - accuracy: 0.3333 - loss: 3.2904
Epoch 10/10
5/5 - 0s - 2ms/step - accuracy: 0.3333 - loss: 3.0868

In [11]:
evaluation_sequential = model_sequential.evaluate(df.iloc[:,0:4], df.iloc[:,4], verbose=2, return_dict=True)

5/5 - 0s - 9ms/step - accuracy: 0.3333 - loss: 1.3231

In [12]:
evaluation_functional = model_functional.evaluate(df.iloc[:,0:4], df.iloc[:,4], verbose=2)

5/5 - 0s - 10ms/step - accuracy: 0.3333 - loss: 2.9633

In [13]:
predictions_sequential = model_sequential.predict(df.iloc[:,0:4])

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [14]:
predictions_functional = model_functional.predict(df.iloc[:,0:4])

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step